# the id is the name of the node, the x and y are the coordination of the node and the u and v 
# represent that there is a relation between the nodes the cost is the distance between these nodes

# VERY IMPORTANT : USE THE GRADES IN GAZEBO AS A CARTESIENNE COORDENENT AND MAKE SURE THAT THE GOALS AREN'T FAR FROM THE ROBOT.

nodes:
  - id: 1
    x: 0.0
    y: 0.0
  - id: 2
    x: -1.0
    y: 8.0
  - id: 3
    x: -7.0
    y: 6.5
  - id: 4
    x: -4.0
    y: 1.0
  - id: 5
    x: -10.0
    y: 2.5
  - id: 6
    x: -9.0
    y: 9.5
  - id: 7
    x: -7.5
    y: 17.0
  - id: 8
    x: -6.5
    y: 20.0
  - id: 9
    x: -2.0
    y: 22.5
  - id: 10
    x: 2.0
    y: 14.0
  - id: 11
    x: -2.0
    y: 0.0

edges:
  - u: 1
    v: 2
    cost: 8.06
  - u: 2
    v: 3
    cost: 4.27
  - u: 3
    v: 4
    cost: 5.59
  - u: 4
    v: 5
    cost: 6.19
  - u: 5
    v: 6
    cost: 7.07
  - u: 6
    v: 7
    cost: 7.65
  - u: 7
    v: 8
    cost: 3.16
  - u: 8
    v: 9
    cost: 5.15
  - u: 9
    v: 10
    cost: 9.85
  - u: 10
    v: 11
    cost: 14.56
  - u: 11
    v: 1
    cost: 2.00
